import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/student_admin/Sidebar";
import Navbar from "@/components/student_admin/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Student Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex  gap-5">
          <Sidebar
            activeItem="dashboard"
            onItemSelect={() => {}}
          />
            <div className="flex flex-col ">
              <Navbar/>
             {children}
            </div>
          
        </div>
      </body>
    </html>
  );
}
